In [1]:
#Goal: Create a mdoel that can classify my customer as good or bad
# based on customer's age and custyomer's estimated salary

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("Social_Network_Ads.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB

In [5]:
data.describe()

              Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [6]:
data.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [7]:
data.Purchased.unique()

array([0, 1])

In [8]:
#Domain expert input
# 0 ----- Bad customer (Customers who window shop and dont do purchase)
# 1 ----- Good Customer (Customer who make a purchase)

In [9]:
#Seperate data as features and label
features = data.iloc[:,[0,1]].values
label = data.iloc[:,[2]].values

In [13]:
#Model Exploration Phase ----- Dr.AI Strage ;)

import warnings
warnings.filterwarnings("ignore")

CL = 0.95

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

for rs in range(1,301):
  X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=rs)

  model = LogisticRegression()
  model.fit(X_train,y_train)

  trainScore = model.score(X_train,y_train)
  testScore = model.score(X_test,y_test)

  if testScore > trainScore and testScore>=CL:
    print(f"Test Score : {testScore} | Train Score: {trainScore} | RandomState: {rs}")

Test Score : 0.9625 | Train Score: 0.81875 | RandomState: 220

In [14]:
#Prepare final Model

X_train,X_test,y_train,y_test = train_test_split(features,
                                                   label,
                                                   test_size=0.2,
                                                   random_state=220)

model = LogisticRegression()
model.fit(X_train,y_train)

trainScore = model.score(X_train,y_train)
testScore = model.score(X_test,y_test)

print(f"Test Score : {testScore} | Train Score: {trainScore} ")

Test Score : 0.9625 | Train Score: 0.81875

In [16]:
#Deploy Test

age = int(input("Enter Age: "))
eSalary = int(input("Enter Estimated Salary: "))

featureInput = np.array([[age,eSalary]])

result = model.predict(featureInput)

#print(result)

"Bad Customer" if result == 0 else "Good Customer"

Enter Age: 45
Enter Estimated Salary: 898999

'Good Customer'